name: Lint-Test-Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Test
        run: go test -v ./...

  cover:
    name: cover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          token: "c3a39bae-5866-4d7d-8cd4-ef523b745f9d"
          directory: .
          file: profile.cover

  build:
    name: build
    runs-on: ubuntu-latest
    environment: unibot-tg
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: go build -v ./...
