name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        token: "c3a39bae-5866-4d7d-8cd4-ef523b745f9d"
        directory: .
        file: profile.cover
        
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Format
      run: gofmt -s -w .    

    - name: Build
      run: go build -v ./...
