name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cover:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: "c3a39bae-5866-4d7d-8cd4-ef523b745f9d"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: CodeCov
      run:  bash <(curl -s https://codecov.io/bash)

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Format
      run: gofmt -s -w .    

    - name: Build
      run: go build -v ./...
